baseURL = 'https://hamana.nl/'
languageCode = 'nl-nl'
title = 'Hamana Cattery'
defaultContentLanguage = 'nl'

[params]
description = "Kleinschalige Ragdoll & Noorse Boskat-cattery in Arnhem die zich inzet voor het fokken van sociale en gezonde kittens."

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'

[[menu.main]]
  identifier = 'niews'
  name = 'Nieuws'
  url = '/nieuws'

[imaging]
anchor = 'Smart'
bgColor = '#ffffff'
hint = 'photo'
quality = 75
resampleFilter = 'Box'